name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - ruff
  - mypy
  - sphinx
  - pre-commit
  - conda-lock
  - ipykernel
  - scanpy
  - anndata
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - umap-learn
  - lightning
  - pyro4
  - pytest
  - pip:
      - pip
      - setuptools
      - wheel
      - scib
prefix: /opt/conda/envs/myenv
platforms:
  - linux-aarch64
  - linux-64
  - osx-64
  - osx-arm64
